### PR TITLE
House map

### PR DESCRIPTION
**Pull request by emilyclaudet**
- Added new house map!!!
- Added characters as objects
- Updated music to suit living room
- Changed spawn point (needs help!)

### CODE REVIEW

**Comment by emilyclaudet** [comment]
@cmclaudet I changed the spawn point so that it's in the piano area. The camera view at the moment is stuck with that part of the map in view for now.

I also changed the conf file to have 768x1024... We'll figure out what makes sense as we develop.

**Comment by cmclaudet** [comment]
I added collisions for the background and the NPC characters :D the camera also tracks the player now. The code is really messy D: I will comment and fix it up later before merging with master

**Comment by cmclaudet** [comment]
Also, the background data comes directly from the house map file - not the instantiated map! Haven't read enough about metatables to understand how to call the background data the way STI wants you to. Would be better to call from the map itself. this is a simple workaround for now.

**Comment by emilyclaudet** [comment]
@cmclaudet ok so for some reason the new tiles that I've added to the Collision layer don't seem to be collidable. 

Nevertheless it's all very exciting to see Christopher's artwork in the game.

**Comment by cmclaudet** [comment]
Oh yeah that's almost certainly because the collisions have been added from the house.lua file in the src directory itself, not the one in the res directory. I created a second one because I couldn't figure out how to loop through the tiles from the instantiated map, so I put a copy of the house.lua file in the same directory as the main to make it easier to work with. It's not ideal and I will change it! Even if we don't use the instantiated map for collisions we still shouldn't need two copies of it.

**Comment by cmclaudet** [comment]
Collisions issue fixed! Check the dialoguereconstruct branch!

**Pull request merged**
